CREATE DATABASE asvanyborze
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_hungarian_ci;

USE asvanyborze;


CREATE TABLE Login (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	FelhasznaloID INT(11) NOT NULL,
	Datum DATETIME NOT NULL,
	Statusz varchar(255) NOT NULL,
	Komment varchar(50) NOT NULL,
	IP varchar(32) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Felhasznalo (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	Nev varchar(25) NOT NULL,
	Jelszo varchar(100) NOT NULL,
	Email varchar(100) NOT NULL,
	Telefon int(32) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Termek (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	TermekNev varchar(100) NOT NULL,
	EladoID INT(11) NOT NULL,
	ArTipus INT(11) DEFAULT NULL,
	Ar INT(11) NOT NULL,
	Tipus INT(11) DEFAULT NULL,
	Asvany INT(11) DEFAULT NULL,
	Helyszin INT(11) DEFAULT NULL,
	Leiras TEXT DEFAULT NULL,
	Kep INT(11) DEFAULT NULL,
  Torles VARCHAR(10) DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Kep (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	Mappa varchar(100) DEFAULT NULL,
	File varchar(100) DEFAULT NULL,
  File1 varchar(100) DEFAULT NULL,
  File2 varchar(100) DEFAULT NULL,
  File3 varchar(100) DEFAULT NULL,
  File4 varchar(100) DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PrivateChat (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	TermekID INT(11) NOT NULL,
	VasarloID INT(11) NOT NULL,
	Uzenet TEXT NOT NULL,
	Datum DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Licitalas (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	VasarloID INT(11) DEFAULT NULL,
	AktualAr INT(11) DEFAULT NULL,
	LicitalasiIdo DATETIME DEFAULT NULL,
	LezarasIdo DATETIME DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Tipus (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	Megnevezes varchar(50) DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE AsvanyTipus (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	AsvanyNev varchar(50) DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Megye (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	MegyeNev varchar(50) DEFAULT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Telepules (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	TelepulesNev varchar(50) DEFAULT NULL,
	MegyeID INT(11) NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE Login ADD CONSTRAINT FK_FelhasznaloID FOREIGN KEY (FelhasznaloID) REFERENCES Felhasznalo(ID);

ALTER TABLE Termek ADD CONSTRAINT FK_EladoID FOREIGN KEY (EladoID) REFERENCES Felhasznalo(ID);

ALTER TABLE Termek ADD CONSTRAINT FK_Tipus FOREIGN KEY (Tipus) REFERENCES Tipus(ID);

ALTER TABLE Termek ADD CONSTRAINT FK_Asvany FOREIGN KEY (Asvany) REFERENCES AsvanyTipus(ID);

ALTER TABLE Termek ADD CONSTRAINT FK_Helyszin FOREIGN KEY (Helyszin) REFERENCES Telepules(ID);

ALTER TABLE Termek ADD CONSTRAINT FK_Kep FOREIGN KEY (Kep) REFERENCES Kep(ID);

ALTER TABLE PrivateChat ADD CONSTRAINT FK_ChatTermekID FOREIGN KEY (TermekID) REFERENCES Termek(ID);

ALTER TABLE PrivateChat ADD CONSTRAINT FK_ChatVasarloID FOREIGN KEY (VasarloID) REFERENCES Felhasznalo(ID);

ALTER TABLE Licitalas ADD CONSTRAINT FK_LicitVasarloID FOREIGN KEY (VasarloID) REFERENCES Felhasznalo(ID);

ALTER TABLE Telepules ADD CONSTRAINT FK_MegyeID FOREIGN KEY (MegyeID) REFERENCES Megye(ID);

